dist: trusty
sudo: required
language: go

go:
  - 1.3 # Debian jessie
  - 1.7 # Debian stretch
  - tip

before_install:
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -yqq libmpv-dev

install:
  - go get github.com/nu7hatch/gouuid
  - go get golang.org/x/crypto/ssh/terminal
